//
//  TictactoeTests.swift
//  TictactoeTests
//
//  Created by Viktoras Laukevičius on 13/12/15.
//
//

import XCTest
import SwiftCheck

class TictactoeTests: XCTestCase {
    
    func testExample() {
        property("The reverse of the reverse of an array is that array") <- forAll { (xs : ArrayOf<Int>) in
            // This property is using a number of SwiftCheck's more interesting
            // features.  `^&&^` is the conjunction operator for properties that turns
            // both properties into a larger property that only holds when both sub-properties
            // hold.  `<?>` is the labelling operator allowing us to name each sub-part
            // in output generated by SwiftCheck.  For example, this property reports:
            //
            // *** Passed 100 tests
            // (100% , Right identity, Left identity)
            return
            (xs.getArray.reverse().reverse() == xs.getArray) <?> "Left identity"
                ^&&^
                (xs.getArray == xs.getArray.reverse().reverse()) <?> "Right identity"
        }
    }
    
}
